starkat99/half-rs

- src/lib.rs
This PR has three commits:
1. Small optimization on `is_nan` and `is_infinite` that saves one comparison in each.
2. Fix comparisons of +0 to -0 and comparisons involving negative numbers. Fixes #2.
3. Update behavior of `is_sign_positive` and `is_sign_negative` to match the update behavior of the standard library. Fixes #3.
> Fix comparisons and behavior of `is_sign_positive`

- src/lib.rs
This commit checks the least significant 32 bits of an `f64` when converting to an `f16` in the case of infinity/overflow to make sure that if any bits in the mantissa are set, the returned `f16` is NaN not infinity. 
It also maintains the sign of an `f32` or an `f64` NaN when converting to an `f16` NaN, and adds some tests.
Fixes #5.
> fix NaN conversion from `f64`, and maintain NaN sign

- src/lib.rs
I'm not sure about the `deprecated(since = "version")`, I guess it would be 1.2.0 so that's what I put in.
Fixes #12.
> rename as_bits -> to_bits

- src/lib.rs
This commit will add support for conversion between slices and vectors of u16 bits and f16 numbers. It should close #14.
Two modules are introduced, `slice` and `vec`. The `vec` module will only be included if the `std` feature is enabled, because vectors require `std`. Each module contains the functions `from_bits` and `to_bits`, like the `f16` type. The contents of the arrays are unsafely cast to the desired type, assuming that in Rust an array of `f16(u16)` will always be represented by an array of `u16` in memory. This is faster than using `into_iter().map(f16::from_bits).collect()`.
The commit also includes some simple tests, which were executed using Rust 1.15.0. More detailed tests should probably be added in the future.
> Convert between arrays of u16 bits and f16 numbers

- src/lib.rs
Mutable slices can be converted without violating mutability rules. Added two functions to convert between mutable `f16` number slices and `u16` bit slices. Closes #16.
> Added functionality to convert between mutable slices

- Cargo.toml
Currently, the vec module is undocumented in docs.rs, because it requires the std feature. This PR makes docs.rs use the std feature when documenting the crate.
> make docs.rs document vec module that requires std feature

- src/lib.rs
The first commit fixes some constants:
* `EPSILON` = 2^−10, its biased exp is 5, so its bits should be `5<<10 = 0x1400`.
* 10^5 <= `MAX` < 10^6, so `MAX_10_EXP` should be 5.
* 10^−5 <= `MIN` < 10^−4, so `MIN_10_EXP` should be −4.
* `MAX_EXP` and `MIN_EXP` are 16, −13, because like C's float.h, `std::f32` assumes the significand is in the range 0.5 ≤ *x* < 1.0. (The text of the IEEE-754 standard uses 1.0 ≤ *x* < 2.0, such that its maximum and minimum exponent values are 15 and −14.)
* `f32::NAN::to_bits()` gives `0x7FC0_0000`, so its equivalent is `0x7E00`.
The second commit fixes some tests that compared the difference between 7.1 representations with `EPSILON`. However `EPSILON` is in relation to 1.0. Since 7 uses two more significant bits than 1, the difference should be compared with 4 …
> Fix constants

- src/bfloat.rs
- src/lib.rs
[bfloat16](https://en.wikipedia.org/wiki/Bfloat16_floating-point_format) is another 16-bit floating point format which has the same number of exponent bits as `f32`, making conversion to/from `f32` much faster. This PR would add support for bfloat16 floats to the crate.
I'm not sure if there is interest in adding this to the half crate, but since the code is basically a tweaked version of the `f16` code, I thought it made sense to add it to the crate.
I'm also not sure about the names. I just prepended `b` to `f16`, `consts`, `slice` and `vec` to get `bf16`, `bconsts`, `bslice` and `bvec`. It looks fine to me, but maybe it makes more sense to keep `bf16` but move the others to `bfloat::consts`, `bfloat::slice` and `bfloat::vec`, I don't know.
> Add support for bfloat16

- src/lib.rs
In conversions from `f32` or `f64` to `f16`, instead of rounding to nearest with ties rounded away from zero, now ties are rounded to even. This can be achieved using only one extra mask check for normal numbers, using a method explained in an inline comment. (For subnormals, `round_bit` is not a constant so it is slightly more expensive, but normals should be the common case.)
Some redundant checks for zero/subnormals were removed as they are perfectly handled by the underflow condition.
Also, when converting NaNs, the most significant 10 bits of the mantissa are retained, then the most significant bit of the mantissa is set. This is similar to what happens when converting an `f32` NaN to `f64`, where the most significant 23 bits of the NaN mantissa are retained, then the most …
> Round to nearest with ties to even

- src/bfloat.rs
- src/lib.rs
This PR makes all NaN conversions behave like NaN conversions between `f32` and `f64`:
* Retain sign.
* Retain as many mantissa bits as possible.
* Set most significant mantissa bit.
In NaN conversion tests, conversion between `f32` and `f64` are included to show that the crate's conversions are consistent with them.
Fixes #23.
> more consistent NaN conversions

- src/bfloat.rs
- src/binary16.rs
Currently this crate wraps an `u16` using a tuple struct into a new type. This is fine, as long the memory representation of this new type is irrelevant (as it is in safe Rust code).
Unfortunately, there is at least one function, that reinterprets an `u16` into a `f16` or `bf16` using casting:
https://github.com/starkat99/half-rs/blob/5f01541c72030584f2160816b9b4c7ee45a4b657/src/vec.rs#L161-L178
At this point, the memory representation of the type is important. Rust does not guarantee, that the wrapping tuple-struct has the same representation as the wrapped type. This possibly leads to undefined behavior!
At this point the `#[repr(transparent)]` attribute is helpful: it serves exactly that purpose to guarantee the same memory layout according to the …
> Add `#[repr(transparent)]` to `f16`/`bf16` types

- src/slice.rs
I'm adding a dependency on half to a large project and wanted to give it a quick
check with miri. The miri stacked borrows checker had an issue with using a non
mutable pointer in the mutable reinterpret cast. Its not clear to me if this
was really indicative of a problem, but the version miri is happy with does look
better to me.
(note there were two other miri failures but they look like a problem
with miri itself - https://github.com/rust-lang/rust/issues/69532)
> Fix as_ptr() -> as_mut_ptr() finding from Miri.

- src/bfloat.rs
- src/binary16.rs
The constants [`f64::consts::LOG10_2`](https://doc.rust-lang.org/nightly/std/f64/consts/constant.LOG10_2.html), [`f64::consts::LOG2_10`](https://doc.rust-lang.org/nightly/std/f64/consts/constant.LOG2_10.html), [`f32::consts::LOG10_2`](https://doc.rust-lang.org/nightly/std/f32/consts/constant.LOG10_2.html) and [`f32::consts::LOG2_10`](https://doc.rust-lang.org/nightly/std/f32/consts/constant.LOG2_10.html) will be stabilized in 1.43.0 in the standard library.
> add LOG10_2 and LOG2_10 constants

- Cargo.toml
- src/bfloat.rs
- src/binary16.rs
Adds optional support for num-traits ToPrimitive / FromPrimitive. This makes it easier to use bf16 and f16 interchangeably with f32.
> Optional num-traits implementations

- Cargo.toml
- src/bfloat.rs
- src/binary16.rs
Adds optional bytemuck Zeroable + Pod implementations for f16 / bf16. This is particularly useful with FFI, and allows safe conversions to bytes and back.
> Optional bytemuck support

- README.md
- src/bfloat.rs
- src/binary16.rs
I've got a crate that allows for being generic over the `Float` trait and it would be nice to have that implemented on these types. I know the readme says that most computations should be done on f32s, and I agree. This just allows for some convenience functions when the `num-traits` feature is enabled and something is generic over some of these extra traits.
(the changes to the `FromPrimitive` implementations were suggested by clippy)
> More num-traits implementations

- README.md
- src/bfloat.rs
- src/binary16.rs
This implements trait [`Bounded`](https://docs.rs/num/0.4.0/num/traits/trait.Bounded.html) for `bf16` and `f16` as the `num-traits` crate implements it for [`f32`](https://github.com/rust-num/num-traits/blob/305532d737f966ea449be2c0f67f575bc66b19a5/src/bounds.rs#L84) and [`f64`](https://github.com/rust-num/num-traits/blob/305532d737f966ea449be2c0f67f575bc66b19a5/src/bounds.rs#L117).
> Implement Bounded trait for bf16 and f16

- src/bfloat.rs
- src/binary16.rs
Since it was missing and all the other numeric traits had reference versions.
> Add `impl Neg` for references

- src/num_traits.rs
Hello!
Thanks for your work on half precision maths :)
This PR adds some missing AsPrimitive implementations: from and to Self, from and to usize and isize.
I was wondering if we should also add AsPrimitivs impls between f16 and bf16, but I'm not sure how we should impl them.
> add AsPrimitive impls: from and to self, from and to usize and isize

- .github/workflows/rust.yml
- src/slice.rs
`slice.as_ptr` goes through a `&[T]`, which only gives it permission to read and not write. Fix it by using `as_mut_ptr` instead.
Also add miri with `MIRIFLAGS=-Zmiri-strict-provenance` to CI.
> Fix unique reference obtained from shared reference 

- src/bfloat.rs
- src/binary16.rs
closes #55
I've adapted the [`std::f32::total_cmp`](https://doc.rust-lang.org/std/primitive.f32.html#method.total_cmp) method for both f16 & bf16 types, including the test example.
Let me know if you prefer something done differently.
> add total_cmp method

- src/bfloat/convert.rs
- src/binary16/convert.rs
I've been inspecting the stack traces in a profiler and noticed that the fallback conversion functions are not inlined.
The `#[inline]` attribute in Rust is [not transitive](https://matklad.github.io/2021/07/09/inline-in-rust.html), and the fallbacks will not be inlined if they are not marked `#[inline]` explicitly. 
I've verified that everything in the call stack up to this point is already marked `#[inline]`.
> Add `#[inline]` on fallback functions

- src/binary16/convert.rs
- src/slice.rs
Removes bounds checks, just like #64. Conflicts with and supersedes #64.
I am interested in this because I'm optimizing the `exr` crate and it would be nice to use these conversion routines directly instead of going through the slice conversion function.
> Use sized slices in conversion functions

- src/bfloat.rs
- src/binary16.rs
Hi, thanks for the great library :grin: 
I've been using [kani](https://github.com/model-checking/kani) to introduce some lightweight formal methods for a CBOR implementation I'm working on. 
Kani has a trait `Arbitrary` which is used to generate symbolic values in the model checker (conceptually, a value that represents "for all `T`s").
The rough motivation for this PR is an enum that looks like:
```rust
#[cfg_attr(kani, derive(kani::Arbitrary))]
enum Float {
Half(half::f16),
Single(f32),
Double(f64),
}
```
This currently fails, since `half::f16` doesn't implement `kani::Arbitrary`. This PR adds the derive macros, gated behind the `kani` compiler option being set. This doesn't add a cargo feature flag or optional dependency, since kani doesn't require this (when you verify a program, it …
> derive kani::Arbitrary on f16 and bf16

- src/leading_zeros.rs
- src/slice.rs
This helps code generation for situations with fixed size arrays:
```rust
let src: [f16; 4];
let mut dst = [0f32; 4];
src.convert_to_f32_slice(&mut dst);
// ^ This will get optimized to a direct f16x4_to_f32x4
```
Without the inline modifier, `convert_to_f32_slice` is always generated as a generic function across arbitrary length slices.
> More #[inline] in HalfFloatSliceExt, leading_zeros

- Cargo.toml
- Makefile.toml
- README.md
- src/lib.rs
- src/rand_distr.rs
- src/sample.rs
Resolves #82 
Tests need to be run with the `sample` and `num-traits` feature enabled
> Adds rand_distr::Distribution implementations for f16 & bf16

- src/bfloat.rs
The original implementation mistakenly computes the product. This pull request fixes this issue.
> Fix Sum<&'a bf16> for bf16

- src/binary16/arch/x86.rs
I was trying to compile this crate for the i686 arch and id did not seem to compile, because a import was missing, (maybe someone did not try to compile for all targets.) I added the import in an extra line, so you can see how you will proceed with this.
Kind regards
> Fixed not compiling for i686-pc-windows-msvc

- src/binary16/convert.rs
- src/slice.rs
- src/vec.rs
Minor improvements to safety and soundness:
- set_len [requires the vector to have been previously initialized](https://doc.rust-lang.org/std/vec/struct.Vec.html#safety-2).
- convert.rs soundness: ensure UB is impossible by checking requirement that array length >=4 . Even if the UB is currently unreachable, future wrong usage can trigger UB.
> Initialize vecs before set_len and check required array length.

- src/num_traits.rs
Adds `AsPrimitive<f16>` for bf16 and `AsPrimitive<bf16>` for f16.
> AsPrimitive f16 <-> bf16

- Cargo.lock
- Cargo.toml
- src/binary16.rs
Preface: Thanks for this crate - it's super fundamental to the ecosystem! ❤️
There are too many fuzzing crates!
This adds support for [rust-fuzz/arbitrary](https://github.com/rust-fuzz/arbitrary) behind a feature flag.
Context:
https://github.com/gfx-rs/wgpu/pull/5701
https://github.com/rust-fuzz/arbitrary/pull/180
> feature: Arbitrary

- Cargo.lock
- Cargo.toml
Allow current releases of `zerocopy` (0.7.x).
> Zerocopy 0.7
